return {}
-- return {
--   "zbirenbaum/copilot.lua",
--   dependencies = {
--     "copilotlsp-nvim/copilot-lsp", -- (optional) for NES functionality
--     init = function()
--         vim.g.copilot_nes_debounce = 500
--         vim.lsp.enable("copilot_ls")
--         -- vim.keymap.set("n", "<tab>", function()
--         --     local bufnr = vim.api.nvim_get_current_buf()
--         --     local state = vim.b[bufnr].nes_state
--         --     if state then
--         --         -- Try to jump to the start of the suggestion edit.
--         --         -- If already at the start, then apply the pending suggestion and jump to the end of the edit.
--         --         local _ = require("copilot-lsp.nes").walk_cursor_start_edit()
--         --             or (
--         --                 require("copilot-lsp.nes").apply_pending_nes()
--         --                 and require("copilot-lsp.nes").walk_cursor_end_edit()
--         --             )
--         --         return nil
--         --     else
--         --         -- Resolving the terminal's inability to distinguish between `TAB` and `<C-i>` in normal mode
--         --         return "<C-i>"
--         --     end
--         -- end, { desc = "Accept Copilot NES suggestion", expr = true })
--     end,
--   },
--   cmd = "Copilot",
--   -- event = "InsertEnter",
--   config = function()
--     require("copilot").setup({
--       nes = {
--         enabled = true,
--         keymap = {
--           -- accept_and_goto = "<leader>p",
--           accept_and_goto = "<tab>",
--           accept = false,
--           dismiss = "<Esc>",
--         },
--       },
--       filetypes = {
--         markdown = true, -- overrides default
--         terraform = false, -- disallow specific filetype
--         sh = function()
--           if string.match(vim.fs.basename(vim.api.nvim_buf_get_name(0)), '^%.env.*') then
--             -- disable for .env files
--             return false
--           end
--           return true
--         end,
--       },
--     })
--   end,
-- }
